name: Android CI

on:
  push:
    branches:
    - master
    - develop 
  pull_request:
    branches:
    - master
    - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: LINT JOB
      run: touch credentials.properties &&
        echo marvel.public.key=\"0000\" >> gradle.properties &&
        echo marvel.private.key=\"0000\" >> gradle.properties &&
        ./gradlew lintDebug
      
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: TEST JOB
      run: touch credentials.properties &&
        echo marvel.public.key=\"0000\" >> gradle.properties &&
        echo marvel.private.key=\"0000\" >> gradle.properties &&
        ./gradlew testDebugUnitTest
